### ISSUE TITLE
pydal_def not generated. yaml2schema interrupted.

### ISSUE THREAD

**Issue by psychedel** [benlawraus/pyDALAnvilWorksDev#1]
Hi,
Awesome project!
How can I solve this issue?
During the "Generate pydal_def.py in the tests directory .."

```
type_col = OPENAPI_TYPES[type_col]
KeyError: 'media'
pydal_def not generated. yaml2schema interrupted.
Errors occurred. Exiting.
```

**Comment by benlawraus** [comment]
Hi
I tried with the multi-user news app linked here on anvil.works [at bottom of page](https://anvil.works/learn/tutorials/multi-user-apps/chapter-3) and it works with media.  Can you send another tutorial app from anvil.works that has a similar usage as your app so that I can repeat the error?
